name: Smoke (prod)

on:
  schedule:
    - cron: "*/15 * * * *"   # every 15 min
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/smoke.sh
